services:
  db:
    container_name: postgresql_db
    image: postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 10
    volumes:
      # Persist database data (keep your bind mount; a named volume also works)
      - ./postgres_data:/var/lib/postgresql/data
      # Run these once on first initialization
      - ./sql:/docker-entrypoint-initdb.d
      # Make CSVs available to COPY during init (read-only)
      - ./data:/docker-entrypoint-initdb.d/data:ro

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db